name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: android_jetpack_compose

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: android_jetpack_compose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KaamMitra-APK
          path: android_jetpack_compose/app/build/outputs/apk/debug/app-debug.apk
